[project]
name = "rzns-yoklama"
version = "0.1.0"
authors = [{ name = "Can Kahraman", email = "brkcnkhrmn@gmail.com" }]
description = "Rezonans Koro Yoklama Takip Sistemi"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.7",
    "django-environ>=0.12.0",
]
