# Generated by Django 5.2.7 on 2025-10-03 20:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="İsim")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Koro Üyesi",
                "verbose_name_plural": "Koro Üyeleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Yoklama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Tarih"
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tarih ve Saat"
                    ),
                ),
                ("present", models.BooleanField(default=True, verbose_name="Katıldı")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yoklama.student",
                        verbose_name="Koro Üyesi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prova Katılımı",
                "verbose_name_plural": "Prova Katılımları",
                "ordering": ["-datetime"],
                "unique_together": {("student", "date")},
            },
        ),
        # prepopulate the Student table with some initial data
        migrations.RunSQL(
            """
            INSERT INTO yoklama_student (name, created_at) VALUES
            ('Gaye Genç', CURRENT_TIMESTAMP),
            ('Eylül Saraçoğlu', CURRENT_TIMESTAMP),
            ('Suat Erhan Demirtaş', CURRENT_TIMESTAMP),
            ('Berdan Kalav', CURRENT_TIMESTAMP),
            ('Pınar Sürmen Akın', CURRENT_TIMESTAMP),
            ('İlkay Tuzcu Tığlı', CURRENT_TIMESTAMP),
            ('Emin Arslan', CURRENT_TIMESTAMP),
            ('Etkin Can Uğurlu', CURRENT_TIMESTAMP),
            ('Seval Ata Demirkan', CURRENT_TIMESTAMP),
            ('Gülçin Erol', CURRENT_TIMESTAMP),
            ('Şerife Derya Yılmaz', CURRENT_TIMESTAMP),
            ('Ezgi Böyükdikmen', CURRENT_TIMESTAMP),
            ('Rana Su Yılmaz', CURRENT_TIMESTAMP),
            ('Uğur Hande Tunçdemir', CURRENT_TIMESTAMP),
            ('Aslıhan Şapaş Aşçı', CURRENT_TIMESTAMP),
            ('Burak Demirkan', CURRENT_TIMESTAMP),
            ('Emir Akın', CURRENT_TIMESTAMP),
            ('Mısra Taşçı', CURRENT_TIMESTAMP),
            ('İris Göğüsgeren', CURRENT_TIMESTAMP),
            ('Mecit Yunus Öztürk', CURRENT_TIMESTAMP),
            ('Burak Can Kahraman', CURRENT_TIMESTAMP),
            ('Zeynep İpek', CURRENT_TIMESTAMP),
            ('Buse Ergül', CURRENT_TIMESTAMP),
            ('Necati Kıvanç Keçeli', CURRENT_TIMESTAMP),
            ('Ayşe Büşra Yakar', CURRENT_TIMESTAMP);
            """,
            reverse_sql="""
            DELETE FROM yoklama_student WHERE name IN (
                'Gaye Genç',
                'Eylül Saraçoğlu',
                'Suat Erhan Demirtaş',
                'Berdan Kalav',
                'Pınar Sürmen Akın',
                'İlkay Tuzcu Tığlı',
                'Emin Arslan',
                'Etkin Can Uğurlu',
                'Seval Ata Demirkan',
                'Gülçin Erol',
                'Şerife Derya Yılmaz',
                'Ezgi Böyükdikmen',
                'Rana Su Yılmaz',
                'Uğur Hande Tunçdemir',
                'Aslıhan Şapaş Aşçı',
                'Burak Demirkan',
                'Emir Akın',
                'Mısra Taşçı',
                'İris Göğüsgeren',
                'Mecit Yunus Öztürk',
                'Burak Can Kahraman',
                'Zeynep İpek',
                'Buse Ergül',
                'Necati Kıvanç Keçeli',
                'Ayşe Büşra Yakar'
            );
            """,
        ),
    ]
